swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: user_controller
    get:
      description: Get all users
      operationId: getUsers
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Add new user
      operationId: addUser
      responses:
        "201":
          description: User added
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{userId}:
    x-swagger-router-controller: user_controller
    get:
      description: Get user by id
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Update user by id
      operationId: updateUserById
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          type: integer
      responses:
        "200":
          description: User updated
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete user by id
      operationId: deleteUserById
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          type: integer
      responses:
        "204":
          description: User deleted
  /images:
      x-swagger-router-controller: image_controller
      get:
        description: Get all images
        operationId: getImages
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      post:
        description: Add new image
        operationId: addImage
        responses:
          "201":
            description: Image added
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /images/{imageId}:
      x-swagger-router-controller: image_controller
      get:
        description: Get image by id
        operationId: getImageById
        parameters:
          - name: imageId
            in: path
            description: image id
            required: true
            type: integer
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      put:
        description: Update image by id
        operationId: updateImageById
        parameters:
          - name: imageId
            in: path
            description: image id
            required: true
            type: integer
        responses:
          "200":
            description: Image updated
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      delete:
        description: Delete image by id
        operationId: deleteImageById
        parameters:
          - name: imageId
            in: path
            description: image id
            required: true
            type: integer
        responses:
          "204":
            description: Image deleted
  /galleries:
      x-swagger-router-controller: gallery_controller
      get:
        description: Get all galleries
        operationId: getGalleries
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      post:
        description: Add new Gallery
        operationId: addGallery
        responses:
          "201":
            description: Gallery added
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /galleries/{galleryId}:
      x-swagger-router-controller: gallery_controller
      get:
        description: Get gallery by id
        operationId: getGalleryById
        parameters:
          - name: galleryId
            in: path
            description: gallery id
            required: true
            type: integer
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      put:
        description: Update gallery by id
        operationId: updateGalleryById
        parameters:
          - name: galleryId
            in: path
            description: gallery id
            required: true
            type: integer
        responses:
          "200":
            description: Gallery updated
            schema:
              $ref: "#/definitions/HelloWorldResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
      delete:
        description: Delete gallery by id
        operationId: deleteGalleryById
        parameters:
          - name: galleryId
            in: path
            description: gallery id
            required: true
            type: integer
        responses:
          "204":
            description: Gallery deleted
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
